# Welcome to Jekyll!

title: 비엣레스트..
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/mywebsite" # the subpath of your site, e.g. /blog
url: "https://thuhoai27.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# permalink 설정
# :title을 사용해 Front Matter의 title에서 슬러그를 생성합니다.
# 파일명(날짜-이름.md)에 영향을 받지 않습니다.
# permalink: /:title/

# Build settings
theme: minima
plugins:
  - jekyll-feed


# posts(기본 글 컬렉션)에도 커스텀 자리표시자를 허용
collections:
  posts:
    output: true
    custom_permalink_placeholders: ["md5title"]

# 전역 퍼머링크 규칙
permalink: /:md5title/
